// Code generated by "stringer -type=ErrLevel"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Fatal-0]
	_ = x[Error-1]
	_ = x[Warning-2]
}

const _ErrLevel_name = "FatalErrorWarning"

var _ErrLevel_index = [...]uint8{0, 5, 10, 17}

func (i ErrLevel) String() string {
	if i < 0 || i >= ErrLevel(len(_ErrLevel_index)-1) {
		return "ErrLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrLevel_name[_ErrLevel_index[i]:_ErrLevel_index[i+1]]
}
